[package]
name = "ntru_crypt"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.82"
base64 = "0.22.0"
clap = { version = "4.5.4", features = ["derive"] }
rand = "0.8.5"
rayon = "1.10.0"
